report:
  policy_name: 'NAC Policy Name'
  owner: ''
  area_of_operation: ''
  # the script will output the file in the same dir where it was ran, specify a path to change where you want to save it at.
  destination_filepath: 'Absolute/Path/ISEDeviceReport.csv'
  send_email: False
  Command_name: 'self'
  prepared_for: 'self'

ise:
  hostname: ''
  ip: ''


authentication:
  text_based:
    use: False
    auth_source: 'Internal'
    username: False
    password: False
  cert_based:
    use: True
    cert_pfx_location: 'ise_client_cert.pfx'
    cert_password: False
  #pipeline use ise_api creds in ise
  pipeline: False

smtp:
  email: ''
  password: False
  server: ''
  port: 25
  destination_email: ''
  destination_email_cc:
    - ''
  body: ''

# if you have custom profiles and want them to fall under another profile for the report in the key value enter the real
# name and  in the value portion enter the name it should go in the report
custom_profiles_match:
  - 'test': 'Unknown'
  - 'test': 'Unknown'
  - test': 'Unknown'
  - 'test': 'Microsoft-Workstation'
  - 'test': 'Microsoft-Workstation'
  - 'test': 'Microsoft-Workstation'

# logical buckets to which endpoints will be matched too. these are created from ISE logical profile
endpoint_buckets_match:
  - 'test'
  - 'test'
  - 'test'
  - 'test'
  - 'test'
  - 'test'
  - 'test'
  - 'unknown'

# if you need a custom report thats already sitting in the repository server
special_reporting:
  use: False
  reporting_location: '/path/to/reports'
  files_to_look_for: 
    - 'test'
  name_of_file_to_send: 'suff_to_send.csv'
  filter_list: 
    - 'useless Col data'
  filter_specifics:
    'ACCT_SESSION_TIME': 0
    'AUTHENTICATION_RULE': 'Allow Guest Users'
  get_attribute_from_endpoint: 'MAC ADDRESS' 

# get all endpoints or just connected ones
only_connected: True


ComplytoConnect:
  step: 1
